using System.Collections.Generic;

namespace ProgressSharp.GameClasses
{
    public static class GameLists
    {
        public static readonly List<string> Titles = new List<string>
        {
            "Mr.",
            "Mrs.",
            "Sir",
            "Sgt.",
            "Ms.",
            "Captain",
            "Chief",
            "Admiral",
            "Saint"
        };

        public static readonly List<string> ImpressiveTitles = new List<string>
        {
            "King",
            "Queen",
            "Lord",
            "Lady",
            "Viceroy",
            "Mayor",
            "Prince",
            "Princess",
            "Chief",
            "Boss",
            "Archbishop"
        };

        public static readonly List<string> BoringItems = new List<string>
        {
            "nail",
            "lunchpail",
            "sock",
            "I.O.U.",
            "cookie",
            "pint",
            "toothpick",
            "writ",
            "newspaper",
            "letter",
            "plank",
            "hat",
            "egg",
            "coin",
            "needle",
            "bucket",
            "ladder",
            "chicken",
            "twig",
            "dirtclod",
            "counterpane",
            "vest",
            "teratoma",
            "bunny",
            "rock",
            "pole",
            "carrot",
            "canoe",
            "inkwell",
            "hoe",
            "bandage",
            "trowel",
            "towel",
            "planter box",
            "anvil",
            "axle",
            "tuppence",
            "casket",
            "nosegay",
            "trinket",
            "credenza",
            "writ"
        };

        public static readonly List<string> Spells = new List<string>
        {
            "Slime Finger",
            "Rabbit Punch",
            "Hastiness",
            "Good Move",
            "Sadness",
            "Seasick",
            "Gyp",
            "Shoelaces",
            "Innoculate",
            "Cone of Annoyance",
            "Magnetic Orb",
            "Invisible Hands",
            "Revolting Cloud",
            "Aqueous Humor",
            "Spectral Miasma",
            "Clever Fellow",
            "Lockjaw",
            "History Lesson",
            "Hydrophobia",
            "Big Sister",
            "Cone of Paste",
            "Mulligan",
            "Nestor's Bright Idea",
            "Holy Batpole",
            "Tumor (Benign)",
            "Braingate",
            "Summon a Bitch",
            "Nonplus",
            "Animate Nightstand",
            "Eye of the Troglodyte",
            "Curse Name",
            "Dropsy",
            "Vitreous Humor",
            "Roger's Grand Illusion",
            "Covet",
            "Astral Miasma",
            "Spectral Oyster",
            "Acrid Hands",
            "Angioplasty",
            "Grognor's Big Day Off",
            "Tumor (Malignant)",
            "Animate Tunic",
            "Ursine Armor",
            "Holy Roller",
            "Tonsilectomy",
            "Curse Family",
            "Infinite Confusion"
        };

        public static readonly List<string> ItemOfs = new List<string>
        {
            "Foreboding",
            "Foreshadowing",
            "Nervousness",
            "Happiness",
            "Torpor",
            "Danger",
            "Craft",
            "Silence",
            "Invisibility",
            "Rapidity",
            "Pleasure",
            "Practicality",
            "Hurting",
            "Joy",
            "Petulance",
            "Intrusion",
            "Chaos",
            "Suffering",
            "Extroversion",
            "Frenzy",
            "Solitude",
            "Punctuality",
            "Efficiency",
            "Comfort",
            "Patience",
            "Internment",
            "Incarceration",
            "Misapprehension",
            "Loyalty",
            "Envy",
            "Acrimony",
            "Worry",
            "Fear",
            "Awe",
            "Guile",
            "Prurience",
            "Fortune",
            "Perspicacity",
            "Domination",
            "Submission",
            "Fealty",
            "Hunger",
            "Despair",
            "Cruelty",
            "Grob",
            "Dignard",
            "Ra",
            "the Bone",
            "Diamonique",
            "Electrum",
            "Hydragyrum"
        };

        public static readonly List<string> ItemAttributres = new List<string>
        {
            "Golden",
            "Gilded",
            "Spectral",
            "Astral",
            "Garlanded",
            "Precious",
            "Crafted",
            "Dual",
            "Filigreed",
            "Cruciate",
            "Arcane",
            "Blessed",
            "Reverential",
            "Lucky",
            "Enchanted",
            "Gleaming",
            "Grandiose",
            "Sacred",
            "Legendary",
            "Mythic",
            "Crystalline",
            "Austere",
            "Ostentatious",
            "One True",
            "Proverbial",
            "Fearsome",
            "Deadly",
            "Benevolent",
            "Unearthly",
            "Magnificent",
            "Iron",
            "Ormolu",
            "Puissant"
        };

        public static readonly List<string> Specials = new List<string>
        {
            "Diadem",
            "Festoon",
            "Gemstone",
            "Phial",
            "Tiara",
            "Scabbard",
            "Arrow",
            "Lens",
            "Lamp",
            "Hymnal",
            "Fleece",
            "Laurel",
            "Brooch",
            "Gimlet",
            "Cobble",
            "Albatross",
            "Brazier",
            "Bandolier",
            "Tome",
            "Garnet",
            "Amethyst",
            "Candelabra",
            "Corset",
            "Sphere",
            "Sceptre",
            "Ankh",
            "Talisman",
            "Orb",
            "Gammel",
            "Ornament",
            "Brocade",
            "Galoon",
            "Bijou",
            "Spangle",
            "Gimcrack",
            "Hood",
            "Vulpeculum"
        };
}
}
